default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
  host: db
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: test_app_development
test:
  <<: *default
  adapter: mysql2
  host: 127.0.0.1
  database: test_app_development
production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
